### ISSUE TITLE
Issues whit the path file of the background

### ISSUE THREAD

**Issue by BregornOriginal** [dqarias/Capstone1-page#1]
Good morning Dino! 

We were watching your code, and it looks so good! nice work doing the capstone and the topic that you choose.

These next changes would help your project to look better. ♻️

Please can you kindly fix the path of the background images, because they are not begin shown?

Maybe if you add a double dot at the beginning of the path it's work, something like ``../`` 

Thank you for your presentation,
Keep coding!💻
> Your morning season group

**Comment by dqarias** [comment]
Hi team;

Thanks for your feedback and help 🎉 . 

I used it in my project and now I don't have problems deploying on the GitHub page.
